### PR TITLE
fix: correct variable name and grammatical errors in deployment.md

### PR DESCRIPTION
**Pull request by intls**
This PR implements issue(s) #

### Description

Resolved several issues in [deployment.md](https://github.com/Consensys/linea-monorepo/blob/main/contracts/docs/deployment.md) file.

* Corrected the variable name from `GOERLI_PRIVATE_KEY` to `LINEA_GOERLI_PRIVATE_KEY` to reflect the appropriate environment variable for the Linea network.
* Replaced incorrect usage of "dependant" with the adjective "dependent".
* Fixed a typo in "delimitted," changing it to "delimited."
* Removed an extra "s" from "addresss," correcting it to "address."

### Checklist

* [ ] I wrote new tests for my new core changes.
* [ ] I have successfully ran tests, style checker and build against my new changes locally.
* [ ] I have informed the team of any breaking changes if there are any.

### CODE REVIEW

**Comment by thedarkjester** [comment]
please update and correct with SEPOLIA etc.

**Comment by intls** [comment]
> please update and correct with SEPOLIA etc.

Hi! @thedarkjester everything is done!

**Comment by thedarkjester** [comment]
> > please update and correct with SEPOLIA etc.
> 
> Hi! @thedarkjester everything is done!

I still see instances where it says GOERLI which was replaced with SEPOLIA. It needs to remain SEPOLIA

**Comment by intls** [comment]
> > > please update and correct with SEPOLIA etc.
> > 
> > 
> > Hi! @thedarkjester everything is done!
> 
> I still see instances where it says GOERLI which was replaced with SEPOLIA. It needs to remain SEPOLIA

Ok, I will make it

**Comment by intls** [comment]
> > > please update and correct with SEPOLIA etc.
> > 
> > 
> > Hi! @thedarkjester everything is done!
> 
> I still see instances where it says GOERLI which was replaced with SEPOLIA. It needs to remain SEPOLIA

@thedarkjester I've done everything! Thanks!

**Review by thedarkjester — APPROVED** [review]

**Pull request merged**
